[2024-07-09 22:58:25,624] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: task2_file_stg.load_peoples manual__2024-07-09T22:58:24.751596+00:00 [queued]>
[2024-07-09 22:58:25,635] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: task2_file_stg.load_peoples manual__2024-07-09T22:58:24.751596+00:00 [queued]>
[2024-07-09 22:58:25,636] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-07-09 22:58:25,637] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2024-07-09 22:58:25,638] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-07-09 22:58:25,650] {taskinstance.py:1259} INFO - Executing <Task(_PythonDecoratedOperator): load_peoples> on 2024-07-09 22:58:24.751596+00:00
[2024-07-09 22:58:25,654] {standard_task_runner.py:52} INFO - Started process 465 to run task
[2024-07-09 22:58:25,659] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'task2_file_stg', 'load_peoples', 'manual__2024-07-09T22:58:24.751596+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/task2_file_stg.py', '--cfg-path', '/tmp/tmpdmnd7uj5', '--error-file', '/tmp/tmpla0rnw0v']
[2024-07-09 22:58:25,664] {standard_task_runner.py:77} INFO - Job 10: Subtask load_peoples
[2024-07-09 22:58:25,727] {logging_mixin.py:109} INFO - Running <TaskInstance: task2_file_stg.load_peoples manual__2024-07-09T22:58:24.751596+00:00 [running]> on host 676d07ac814a
[2024-07-09 22:58:25,791] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=task2_file_stg
AIRFLOW_CTX_TASK_ID=load_peoples
AIRFLOW_CTX_EXECUTION_DATE=2024-07-09T22:58:24.751596+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-07-09T22:58:24.751596+00:00
[2024-07-09 22:58:25,823] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/decorators/base.py", line 134, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/task2_file_stg.py", line 53, in load_peoples
    load_csv_to_vertica("dags/files/people.csv", "peoples")
  File "/opt/airflow/dags/task2_file_stg.py", line 26, in load_csv_to_vertica
    with open(file_path, 'r',encoding="cp-1251") as f:
LookupError: unknown encoding: cp-1251
[2024-07-09 22:58:25,840] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=task2_file_stg, task_id=load_peoples, execution_date=20240709T225824, start_date=20240709T225825, end_date=20240709T225825
[2024-07-09 22:58:25,854] {standard_task_runner.py:92} ERROR - Failed to execute job 10 for task load_peoples
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/decorators/base.py", line 134, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/task2_file_stg.py", line 53, in load_peoples
    load_csv_to_vertica("dags/files/people.csv", "peoples")
  File "/opt/airflow/dags/task2_file_stg.py", line 26, in load_csv_to_vertica
    with open(file_path, 'r',encoding="cp-1251") as f:
LookupError: unknown encoding: cp-1251
[2024-07-09 22:58:25,879] {local_task_job.py:154} INFO - Task exited with return code 1
[2024-07-09 22:58:25,933] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
