[2024-08-12 21:44:55,297] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: load_dds_to_cdm.get_user_age_groups scheduled__2024-08-12T21:44:51.820492+00:00 [queued]>
[2024-08-12 21:44:55,310] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: load_dds_to_cdm.get_user_age_groups scheduled__2024-08-12T21:44:51.820492+00:00 [queued]>
[2024-08-12 21:44:55,311] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-08-12 21:44:55,312] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2024-08-12 21:44:55,312] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-08-12 21:44:55,338] {taskinstance.py:1259} INFO - Executing <Task(_PythonDecoratedOperator): get_user_age_groups> on 2024-08-12 21:44:51.820492+00:00
[2024-08-12 21:44:55,345] {standard_task_runner.py:52} INFO - Started process 2066 to run task
[2024-08-12 21:44:55,351] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'load_dds_to_cdm', 'get_user_age_groups', 'scheduled__2024-08-12T21:44:51.820492+00:00', '--job-id', '62', '--raw', '--subdir', 'DAGS_FOLDER/load_dds_to_cdm.py', '--cfg-path', '/tmp/tmp8xbckwtm', '--error-file', '/tmp/tmpuxwexbnk']
[2024-08-12 21:44:55,360] {standard_task_runner.py:77} INFO - Job 62: Subtask get_user_age_groups
[2024-08-12 21:44:55,458] {logging_mixin.py:109} INFO - Running <TaskInstance: load_dds_to_cdm.get_user_age_groups scheduled__2024-08-12T21:44:51.820492+00:00 [running]> on host 915f51171463
[2024-08-12 21:44:55,556] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=load_dds_to_cdm
AIRFLOW_CTX_TASK_ID=get_user_age_groups
AIRFLOW_CTX_EXECUTION_DATE=2024-08-12T21:44:51.820492+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-08-12T21:44:51.820492+00:00
[2024-08-12 21:44:55,633] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/decorators/base.py", line 134, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/load_dds_to_cdm.py", line 85, in get_user_age_groups
    create_view_users_with_age(connection)
  File "/opt/airflow/dags/load_dds_to_cdm.py", line 58, in create_view_users_with_age
    connection.cursor().execute(query)
  File "/home/airflow/.local/lib/python3.6/site-packages/vertica_python/vertica/cursor.py", line 238, in execute
    self._execute_simple_query(operation)
  File "/home/airflow/.local/lib/python3.6/site-packages/vertica_python/vertica/cursor.py", line 660, in _execute_simple_query
    raise errors.QueryError.from_error_response(self._message, query)
vertica_python.errors.MissingRelation: Severity: ERROR, Message: Relation "public.s_person_info" does not exist, Sqlstate: 42V01, Routine: throwRelationDoesNotExist, File: /data/jenkins/workspace/RE-ReleaseBuilds/RE-Miner/server/vertica/Catalog/CatalogLookup.cpp, Line: 4327, Error Code: 4568, SQL: "         CREATE OR REPLACE VIEW user_age_distribution AS         SELECT             hk_person_id,             CASE                 WHEN DATEDIFF('year', date_of_birthday, CURRENT_DATE) BETWEEN 0 AND 17 THEN '0-17'                 WHEN DATEDIFF('year', date_of_birthday, CURRENT_DATE) BETWEEN 18 AND 24 THEN '18-24'                 WHEN DATEDIFF('year', date_of_birthday, CURRENT_DATE) BETWEEN 25 AND 34 THEN '25-34'                 WHEN DATEDIFF('year', date_of_birthday, CURRENT_DATE) BETWEEN 35 AND 44 THEN '35-44'                 WHEN DATEDIFF('year', date_of_birthday, CURRENT_DATE) BETWEEN 45 AND 54 THEN '45-54'                 WHEN DATEDIFF('year', date_of_birthday, CURRENT_DATE) BETWEEN 55 AND 64 THEN '55-64'                 ELSE '65+'                 END AS age_group         FROM public.s_person_info;         "
[2024-08-12 21:44:55,659] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=load_dds_to_cdm, task_id=get_user_age_groups, execution_date=20240812T214451, start_date=20240812T214455, end_date=20240812T214455
[2024-08-12 21:44:55,678] {standard_task_runner.py:92} ERROR - Failed to execute job 62 for task get_user_age_groups
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/decorators/base.py", line 134, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/load_dds_to_cdm.py", line 85, in get_user_age_groups
    create_view_users_with_age(connection)
  File "/opt/airflow/dags/load_dds_to_cdm.py", line 58, in create_view_users_with_age
    connection.cursor().execute(query)
  File "/home/airflow/.local/lib/python3.6/site-packages/vertica_python/vertica/cursor.py", line 238, in execute
    self._execute_simple_query(operation)
  File "/home/airflow/.local/lib/python3.6/site-packages/vertica_python/vertica/cursor.py", line 660, in _execute_simple_query
    raise errors.QueryError.from_error_response(self._message, query)
vertica_python.errors.MissingRelation: Severity: ERROR, Message: Relation "public.s_person_info" does not exist, Sqlstate: 42V01, Routine: throwRelationDoesNotExist, File: /data/jenkins/workspace/RE-ReleaseBuilds/RE-Miner/server/vertica/Catalog/CatalogLookup.cpp, Line: 4327, Error Code: 4568, SQL: "         CREATE OR REPLACE VIEW user_age_distribution AS         SELECT             hk_person_id,             CASE                 WHEN DATEDIFF('year', date_of_birthday, CURRENT_DATE) BETWEEN 0 AND 17 THEN '0-17'                 WHEN DATEDIFF('year', date_of_birthday, CURRENT_DATE) BETWEEN 18 AND 24 THEN '18-24'                 WHEN DATEDIFF('year', date_of_birthday, CURRENT_DATE) BETWEEN 25 AND 34 THEN '25-34'                 WHEN DATEDIFF('year', date_of_birthday, CURRENT_DATE) BETWEEN 35 AND 44 THEN '35-44'                 WHEN DATEDIFF('year', date_of_birthday, CURRENT_DATE) BETWEEN 45 AND 54 THEN '45-54'                 WHEN DATEDIFF('year', date_of_birthday, CURRENT_DATE) BETWEEN 55 AND 64 THEN '55-64'                 ELSE '65+'                 END AS age_group         FROM public.s_person_info;         "
[2024-08-12 21:44:55,701] {local_task_job.py:154} INFO - Task exited with return code 1
[2024-08-12 21:44:55,785] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
